title = "Anonymous IPFS Blog"
description = "A decentralized blog powered by IPFS"
author = "Anonymous"
base_url = "http://localhost:9000"
base_path = ""  # 本地开发不需要 base_path
ipfs_gateway = "https://ipfs.io/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "hacker"