title = "My IPFS Blog"
description = "A decentralized blog powered by IPFS"
author = "Anonymous"
# Replace DaviRain-Su with your GitHub username for GitHub Pages
base_url = "https://DaviRain-Su.github.io/kpgb"
ipfs_gateway = "https://ipfs.io/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "default"
# Enable CORS for external access
enable_cors = true
# Enable search functionality
enable_search = true
