title = "Anonymous IPFS Blog"
description = "A decentralized blog powered by IPFS"
author = "Anonymous"
base_url = "https://Anonymous.github.io/kpgb"
base_path = "/kpgb"
ipfs_gateway = "https://ipfs.io/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "hacker"                                     # Options: default, hacker, minimal, dark, cyberpunk

# Giscus comment system configuration
[giscus]
enabled = true
repo = "davirain-su/kpgb"            # Your GitHub username/repo
repo_id = "R_kgDOPP4-yg"             # Will be filled after setup
category = "General"                 # Or "General"
category_id = "DIC_kwDOPP4-ys4CtTKw" # Will be filled after setup
mapping = "pathname"                 # How to map posts to discussions
reactions_enabled = true             # Enable emoji reactions
emit_metadata = false                # Whether to emit metadata
input_position = "bottom"            # Comment box position: top or bottom
theme = "preferred_color_scheme"     # Follow site theme
lang = "zh-CN"                       # Language: zh-CN, en, etc.
