title = "DaviRain's Blog"
description = "探索技术、分享思考 - A decentralized blog powered by IPFS"
author = "DaviRain-Su"
base_url = "https://DaviRain-Su.github.io/kpgb"
base_path = "/kpgb"
ipfs_gateway = "https://ipfs.io/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "minimal"                                    # Options: default, hacker, minimal, dark, cyberpunk
