title = "My IPFS Blog"
description = "A decentralized blog powered by IPFS"
author = "Anonymous"
base_url = "http://localhost:8080"
ipfs_gateway = "http://localhost:8080/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "default"
