title = "Anonymous IPFS Blog"
description = "A decentralized blog powered by IPFS"
author = "Anonymous"
base_url = "https://Anonymous.github.io/kpgb"
base_path = "/kpgb"
ipfs_gateway = "https://ipfs.io/ipfs/"
posts_per_page = 10
enable_rss = true
theme = "dark"  # Options: default, hacker, minimal, dark, cyberpunk